language: c

os:
  - linux

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libssl-dev libev-dev

script:
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
